package com.wefluent.wefluent.constants;

/**
 * Generated by RemoteConfig.jar
 */

public abstract class RemoteConfig {

	public static final String welcome_message_caps = "welcome_message_caps";

	public static final String is_app_enabled = "is_app_enabled";


}
